services:
  app:
    volumes:
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
      XDEBUG_CLIENT_PORT: 9003


  websocket:
    volumes:
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
      XDEBUG_TRIGGER: "1"
      XDEBUG_CLIENT_PORT: 9004
